# Site settings
title: Nickolas Gupton
tagline:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nickolasgupton.me" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]
exclude: [vendor]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
