## Site settings
title: Nickolas Gupton
tagline:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nickolas.gupton.xyz" # the base hostname & protocol for your site

## Plugins
plugins: [jekyll-paginate]
exclude: [vendor]

## Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

## Pagination
paginate: 4
paginate_path: "/blog/page:num/"
