## Site settings
title: Nickolas Gupton
tagline: Nickolas Gupton's Website and Blog
description: My home on the Internet. Discussing programming, Linux, and other tech topics.
url: "https://nickolas.gupton.xyz"

## Plugins
plugins: [jekyll-paginate, jekyll-tidy]
exclude: [vendor]

## Build settings
markdown: kramdown

## Pagination
paginate: 4
paginate_path: "/blog/page:num/"

## Tidy
jekyll_tidy:
  compress_html: false

exclude:
  - README.md
