name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  buildDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Cache
      uses: actions/cache@v3.0.1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build and deploy the site
      uses: helaili/jekyll-action@2.3.1
      with:
        token: ${{ secrets.PAT }}
        target_branch: 'gh-pages'