name: Post Deploy
on:
  page_build:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  htmlproofer:
    name: HTMLProofer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Test the generated HTML for errors
        uses: chabad360/htmlproofer@master
        with:
          directory: "/home/runner/work/CorruptComputer.GitHub.io/CorruptComputer.GitHub.io"
          arguments: --http_status_ignore="403,999"
